using System.Reflection;

namespace Demo
{
    internal class Program
    {
        static void Main(string[] args)
        {

            #region Part 06 Class

            #region Ex01

            //Car c1;
            ///// Declare special variable (Reference) of type "Car" in STACK.
            ///// This Reference can refer to object of type "Car" or object of any type inherit from "Car".
            ///// CLR will allocate 4 uninitialized bytes in STACK for this reference "c1" - Those Uninitialized bytes contain Garbage
            ///// CLR will allocate 0 bytes in HEAP because the reference "c1" not refer to object in HEAP - not hold address of any object in heap.

            //c1 = new Car();//The empty parameterless constructor called [auto generated by compiler because i don't write user define constructor inside "Car" class - if you define constructor this line will give error because compiler will not generate empty parameter less constructor, so to solve error you need to define it]. 
            ////In this line you tell compiler to make "new" object in heap based on "Car" Template.
            /////CLR Will Do 4 Things => 
            /////1- Allocate required number of bytes of the allocated object in HEAP (16 Byte)
            /////          int id; =>        4Byte        
            /////          string? model; => 4Byte (because model is reference in stack)
            /////          double speed; =>  8Byte
            /////
            /////2- Initialize (cross out) the allocated bytes for each and every attribute with the default value of attribute data type.
            /////          int id = 0;
            /////          string? model = null;
            /////          double speed = 0;
            /////
            /////3- Call user defined constructor [if exists].
            /////
            /////4- Return the address of the allocated object in heap to the reference in stack "c1".

            //Console.WriteLine(c1);//(Id = 0) - (Model =) - (Speed = 0) 

            #endregion

            #region Ex02

            //Car c2 = new Car(10010, "NissanSunny", 180);//Call the user define constructor.

            //Console.WriteLine(c2);// (Id = 10010) - (Model = NissanSunny) - (Speed = 180)

            #endregion

            #region Ex03 - Constructor Chaining

            //Car c3 = new Car(100);//Constructor 1
            //                         //Constructor 2
            //                         //Constructor 3

            ////When Create object using this constructor (3rd constructor), the chaining constructor (2nd constructor) which (3rd constructor) chain on it will executed first
            ////and we found that (2nd constructor) chain on (1st constructor), so the (1st constructor) will executed first before (2nd constructor) and then go back to execute (2nd constructor & 3rd constructor). 

            //Console.WriteLine(c3);//(Id = 100) - (Model = Kia scerato) - (Speed = 120)

            #endregion

            #endregion

        }
    }
}
